version: '2'
services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    ports: 
      - "8080:8080"
    network_node: host
  read-service:
    build:
      context: .
      dockerfile: Dockerfile.readservice
    ports: 
      - "8020:8020"
    network_node: host
  write-service:
    build:
      context: .
      dockerfile: Dockerfile.writeservice
    ports: 
      - "8030:8030"
    network_node: host
