version: '2'
services:
  consul1:
    image: "progrium/consul:latest"
    container_name: "consul1"
    hostname: "consul1"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:53"
    command: "-server -bootstrap -ui-dir /ui"
  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile.gateway
    ports:
      - "8080:8080"
    network_mode: host
  read-service:
    build:
      context: .
      dockerfile: read-service-graph/Dockerfile.readservice
    ports:
      - "8020:8020"
    network_mode: host
  write-service:
    build:
      context: .
      dockerfile: write-service-graph/Dockerfile.writeservice
    ports:
      - "8030:8030"
    network_mode: host
